### ISSUE TITLE
advanced filtering in file name

### ISSUE THREAD

**Issue by senmao** [gacarrillor/loadthemall#4]
Hi,

Recently I tried to load some files which start with "D" and have "MEAN" in the middle and end with "T1.tif" and can't find a solution with the current filter function which combine these three conditions. It would be nice to have some advanced filter function, for example filtering by regex or similar pattern used by python glob function.

Thanks,
Senmao

**Comment by gacarrillor** [comment]
Hi Senmao, 

thanks for asking. So, we have these requirements: 

- Start with "D"
- "MEAN" in the middle
- End with "T1" (not with T1.tif, because the extension is handled by `Format` option)

Your Filter string could be:

> ^D && MEAN && T1$

Make sure you choose `In any position` option. Additionally, have a look at option `Ignore case in alphanumeric filter` in `Configuration` tab, if you want to set your filter as case insensitive.

Let me know if this solves the issue.

Regards, 

Germán

**Comment by senmao** [comment]
Hi Germán,

Great! I just had a try and it works perfectly.

Thanks a lot!
Senmao

**Comment by gacarrillor** [comment]
Hi Senmao, 

you're welcome. Keep in touch if you have other questions/suggestions.

Regards,
Germán
